version: '3.8'


services:
  service1:
    build: ./service1
    image: service1:latest
    ports: 
      - 3000:3000
  
  service2:
    build: ./service2
    ports: 
      - 3001:3000
    image: service2:latest
   
    
  service3:
    build: ./service3
    image: service3:latest
    ports: 
      - 3002:3000

    

# version: '3.8'

# networks:
#   service-net:
#     driver: bridge

# services:
#   service1:
#     build: ./service1
#     image: service1:latest
#     networks:
#       - service-net
#     ports: 
#       - 3000:3000
  
#   service2:
#     build: ./service2
#     ports: 
#       - 3001:3000
#     image: service2:latest
#     networks:
#       - service-net
    
#   service3:
#     build: ./service3
#     image: service3:latest
#     networks:
#       - service-net
#     ports: 
#       - 3002:3000

    
